**Programació numèrica, dataframes i anàlisi estadístic**

*Tasca 1*

- Exercici 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.


- Exercici 2
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.


- Exercici 3
Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.


- Exercici 4
Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.

In [1]:
import numpy as np
from scipy import stats
import random


__Exercici 1__

Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.


In [2]:
def array_summary(array):
    if array.ndim > 1:
        print('Error, array de més d\' una dimensió')
    else: 
        mean = np.mean(array)
        median = np.median(array) 
        mode = stats.mode(array)[0][0]
        std = np.std(array)
        var = np.var(array)
        skew = stats.skew(array)
        
        text = 'Resum estadístic del array:\nMitjana: ' + str(mean) + '\nMediana: ' + str(median) + '\nModa:' + str(mode) + '\nDesviació típica:' + str(std) + '\nVariança: ' + str(var) + '\nAsimetria: ' + str(skew)
        print(text)


In [3]:
array = np.array([2, 4, 5, 6, 2, 1, 9])
array_summary(array)

Resum estadístic del array:
Mitjana: 4.142857142857143
Mediana: 4.0
Moda:2
Desviació típica:2.5872528966106905
Variança: 6.6938775510204085
Asimetria: 0.5848157341219765


__Exercici 2__

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [4]:
def random_array(num):
    arr = np.zeros((num, num))
    print(arr)
    for i in range(0, num):
        row = []
        for j in range(0, num):
            row.append(random.randint(0, 100))
            print(row)
        np.append(arr, np.array(row))
    print(arr)

In [5]:
def random_array(num):
    arr = []
    for i in range(0, num):
        row = []
        for j in range(0, num):
            row.append(random.randint(0, 100))
        arr.append(row)
    arr = np.array(arr)
    return arr

In [6]:
print(random_array(15))

[[ 84  81  71   7  92  97  45  31  88  97  78  44  87  97  11]
 [ 37  88  60  29  24 100  84  28  82  43  46  41  31  16  77]
 [ 30  73  21  54  53  20  58  66  17  50  18  49  99  10  49]
 [ 38  93  81   7  29  49  82  18  84  57  35  43  69  56  67]
 [ 74  53   5  20  73  10 100  33  78  20  36  57  86  15  14]
 [ 79  74  53  52  11  36  89   0  47  22  73   8  63  25  67]
 [ 91  44  21  87  20  60  90  49  67  69  77  58  49  99   6]
 [ 50  49  89  37  77   5  43  26  23  79  54   0  83  71  59]
 [ 63   3   7  96  49  12  94  19  12  10  99  52  49  57  29]
 [ 43  60  76  57  69  60  81  84   3  57  45  36 100   7   1]
 [ 77  50   9  52  46   3  28  79  63  23  19  72  42  57  93]
 [  2  24  90  45  38  72  37  21  13  10  12  60  28  28  57]
 [ 62  10  74  78  92  93  87  73  55  89  28   5  79  16  54]
 [ 31  84  74  47   2  47  40  42  29  34  64   0   9  47  24]
 [ 53  61  79  58  69  86  93  24  66  84  70  11  56  47  67]]


In [7]:
random.randint(0, 100)

90

__Exercici 3__

Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

In [8]:
def random_array_2(rows, cols):
    arr = []
    for i in range(0, rows):
        row = []
        for j in range(0, cols):
            row.append(random.randint(0, 100))
        arr.append(row)
    arr = np.array(arr)
    return(arr)
    
def sums(arr):
    col_sum = np.sum(arr, axis = 0)
    row_sum = np.sum(arr, axis = 1)
    
    print('Suma de les columnes')
    print(col_sum)
    print('Suma de les files')
    print(row_sum)

In [9]:
sums(random_array_2(2, 3))

Suma de les columnes
[ 57 121 141]
Suma de les files
[183 136]


__Exercici 4__

Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.

In [10]:
# Intent 1

arr = np.array(random_array_2(2, 10))

#Calculem la mitjana de cada columna:

x_mean = 0
y_mean = 0

for i in range (0, len(arr[0])):
    x_mean += arr[0][i]/len(arr[0])

for i in range (0, len(arr[0])):
    y_mean += arr[1][i]/len(arr[1])

# Calculem la covariança. Primer els operadors del numerador:

oper_x = 0
oper_y = 0

for i in range (0, len(arr[0])):
    oper_x += arr[0][i] - x_mean

for i in range (0, len(arr[0])):
    oper_y += arr[1][i] - y_mean 
    
cov_xy = (oper_x * oper_y) / len(arr[0])

#Calculem la desviació estandard

num_x = 0

num_x += (arr[0][i] - x_mean)**2

num_y = 0

num_y += (arr[1][i] - y_mean)**2

desv_x = np.sqrt(num_x/len(arr[0]))
print(desv_x)
print(np.std(arr[0]))
desv_y = np.sqrt(num_y/len(arr[1]))
print(desv_y)
print(np.std(arr[1]))
print(np.std(arr, 1))

# Càlcul correlació

corr = cov_xy / (desv_x * desv_y)

print(corr)
print(np.corrcoef(arr[0], arr[1]))

2.1503488089144995
25.05913007269007
4.3323203944306785
25.243018836898255
[25.05913007 25.24301884]
2.276146536318247e-29
[[1.        0.2512931]
 [0.2512931 1.       ]]


In [11]:
# Intent 2

arr = np.array(random_array_2(2, 10))
#arr = np.array([[7, 14, 32, 52, 85, 91, 105, 121], [1, 2, 3, 3, 5, 5, 6, 6]])
arr = np.array([[22, 48, 76, 10, 22, 4, 68, 44, 10, 76, 14, 56], [63, 39, 61, 30, 51, 44, 74, 78, 55, 58, 41, 69]])

#Calculem la mitjana de cada columna:

x_mean = 0
y_mean = 0

for i in range (0, len(arr[0])):
    x_mean += arr[0][i]
    
x_mean = x_mean / len(arr[0])

for i in range (0, len(arr[0])):
    y_mean += arr[1][i]
    
y_mean = y_mean / len(arr[1])

print('x_mean')
print(x_mean)

print('y_mean')
print(y_mean)

# Calculem la covariança. Primer els operadors del numerador:

oper_x = 0
oper_y = 0
cov_xy = 0

for i in range (0, len(arr[0])):
    cov_xy += ((arr[0][i] - x_mean) * (arr[1][i] - y_mean)) / len(arr[0])
    
print('cov_xy')
print(cov_xy)

#Calculem la desviació estandar

num_x = 0
num_y = 0

for i in range (0, len(arr[0])):
    num_x += (arr[0][i] - x_mean)**2

for i in range (0, len(arr[0])):
    num_y += (arr[1][i] - y_mean)**2

desv_x = np.sqrt(num_x/len(arr[0]))
print(desv_x)
print(np.std(arr[0]))
desv_y = np.sqrt(num_y/len(arr[1]))
print(desv_y)
print(np.std(arr[1]))
print(np.std(arr, 1))

# Calculem la correlació

corr = cov_xy / (desv_x * desv_y)

print(corr)
print(np.corrcoef(arr[0], arr[1]))

x_mean
37.5
y_mean
55.25
cov_xy
207.45833333333331
25.911709064951054
25.911709064951054
14.16642156650719
14.16642156650719
[25.91170906 14.16642157]
0.5651642265418636
[[1.         0.56516423]
 [0.56516423 1.        ]]


In [12]:
# Format funció

def manual_corr(arr):

    #Calculem la mitjana de cada columna:

    x_mean = 0
    y_mean = 0

    for i in range (0, len(arr[0])):
        x_mean += arr[0][i]

    x_mean = x_mean / len(arr[0])

    for i in range (0, len(arr[0])):
        y_mean += arr[1][i]

    y_mean = y_mean / len(arr[1])

    # Calculem la covariança. Primer els operadors del numerador:

    oper_x = 0
    oper_y = 0
    cov_xy = 0

    for i in range (0, len(arr[0])):
        cov_xy += (arr[0][i] - x_mean) * (arr[1][i] - y_mean) / len(arr[0])

    #Calculem la desviació estandar

    num_x = 0
    num_y = 0

    for i in range (0, len(arr[0])):
        num_x += (arr[0][i] - x_mean)**2

    for i in range (0, len(arr[1])):
        num_y += (arr[1][i] - y_mean)**2

    desv_x = np.sqrt(num_x/len(arr[0]))

    desv_y = np.sqrt(num_y/len(arr[1]))

    # Calculem la correlació

    corr = cov_xy / (desv_x * desv_y)

    print(corr)
    return corr

In [13]:
# Proves càlcul manual correlació

arr_1 = random_array_2(2, 10)

arr_2 = np.array([[7, 14, 32, 52, 85, 91, 105, 121], [1, 2, 3, 3, 5, 5, 6, 6]])

arr_3 = np.array([[7, 14, 32, 52, 85, 91, 105, 121], [5, 5, 4, 3, 3, 2, 1, 0]])

print('Test random. Les variables, al prendre valors aleatoris, no mostraran correlació')
print('Correlació manual')
manual_corr(arr_1)
print('Correlació amb la funció de Numpy')
print(np.corrcoef(arr_1[0], arr_1[1]))

print('Test correlació positiva. Les dades de les variables estan correlacionades de tal forma que al creixer una, també ho fa l\'altra')
manual_corr(arr_2)
print(np.corrcoef(arr_2[0], arr_2[1]))

print('Test correlació negativa. Les dades de les variables estan correlacionades de tal forma que al creixer una, l\'altra decreix')
manual_corr(arr_3)
print(np.corrcoef(arr_3[0], arr_3[1]))


Test random. Les variables, al prendre valors aleatoris, no mostraran correlació
Correlació manual
-0.16906838690817289
Correlació amb la funció de Numpy
[[ 1.         -0.16906839]
 [-0.16906839  1.        ]]
Test correlació positiva. Les dades de les variables estan correlacionades de tal forma que al creixer una, també ho fa l'altra
0.9813888179844993
[[1.         0.98138882]
 [0.98138882 1.        ]]
Test correlació negativa. Les dades de les variables estan correlacionades de tal forma que al creixer una, l'altra decreix
-0.9652006490640259
[[ 1.         -0.96520065]
 [-0.96520065  1.        ]]


In [14]:
arr

array([[22, 48, 76, 10, 22,  4, 68, 44, 10, 76, 14, 56],
       [63, 39, 61, 30, 51, 44, 74, 78, 55, 58, 41, 69]])

In [15]:
len(arr[0])

12

In [16]:
k_m = np.array([22, 48, 76, 10, 22, 4, 68, 44, 10, 76, 14, 56])
km = np.array([63, 39, 61, 30, 51, 44, 74, 78, 55, 58, 41, 69])

gns_k_m = 0
gns_km = 0
cov = 0
sum_k_m = 0
sum_km = 0

for k in range(len(k_m)):
    gns_k_m += k_m[k]/len(k_m)

for k in range(len(km)):
    gns_km += km[k]/len(km)
    
print(gns_k_m, gns_km)

for k in range(len(k_m)):
    cov += (k_m[k]-gns_k_m)*(km[k]-gns_km)/(len(k_m))

print(cov)

for k in range(len(k_m)):
    sum_k_m += (k_m[k]-gns_k_m)**2

sa_k_m = np.sqrt(sum_k_m/len(k_m))
print(sa_k_m)
print(np.std(k_m))

for k in range(len(km)):
    sum_km += (km[k]-gns_km)**2
    
sa_km = np.sqrt(sum_km/len(km))
print(sa_km)
print(np.std(km))

cor = cov/(sa_k_m*sa_km)

print(cor)
print(np.corrcoef(k_m,km))

37.5 55.25000000000001
207.45833333333334
25.911709064951054
25.911709064951054
14.16642156650719
14.16642156650719
0.5651642265418636
[[1.         0.56516423]
 [0.56516423 1.        ]]
