___Sprint 3___

**Programació numèrica, dataframes i anàlisi estadístic**

*Tasca 1*

- Exercici 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.


- Exercici 2
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.


- Exercici 3
Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.


- Exercici 4
Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.

In [1]:
import numpy as np
from scipy import stats
import random


__Exercici 1__

Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.


In [2]:
def array_summary(array):
    if array.ndim > 1:
        print('Error, array de més d\' una dimensió')
    else: 
        mean = np.mean(array)
        median = np.median(array) 
        mode = stats.mode(array)[0][0]
        std = np.std(array)
        var = np.var(array)
        skew = stats.skew(array)
        
        text = 'Resum estadístic del array:\nMitjana: ' + str(mean) + '\nMediana: ' + str(median) + '\nModa:' + str(mode) + '\nDesviació típica:' + str(std) + '\nVariança: ' + str(var) + '\nAsimetria: ' + str(skew)
        print(text)


In [3]:
array = np.array([2, 4, 5, 6, 2, 1, 9])
array_summary(array)

Resum estadístic del array:
Mitjana: 4.142857142857143
Mediana: 4.0
Moda:2
Desviació típica:2.5872528966106905
Variança: 6.6938775510204085
Asimetria: 0.5848157341219765


__Exercici 2__

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [4]:
def random_array(num):
    arr = np.zeros((num, num))
    print(arr)
    for i in range(0, num):
        row = []
        for j in range(0, num):
            row.append(random.randint(0, 100))
            print(row)
        np.append(arr, np.array(row))
    print(arr)

In [5]:
def random_array(num):
    arr = []
    for i in range(0, num):
        row = []
        for j in range(0, num):
            row.append(random.randint(0, 100))
        arr.append(row)
    arr = np.array(arr)
    return arr

In [6]:
print(random_array(15))

[[ 31  38  53  70  91  24  73   6 100  97  12  23  79  19  57]
 [ 74   3  18  86  44  19  39  87  43  87  41  49  83  54   5]
 [ 20  48   9  42  91   2  52  35  66  66  96 100  83  72  42]
 [ 81  27  64  89  51  41  98  43  71  51  43  13  39  18  29]
 [ 42  92  78  97  46  48   8   7  71  58  69  10  20  81  10]
 [ 31  96  21  23  95  29  37  32  24  48  27  31  16  29  30]
 [ 65   3  97  24  84  83  97   2  60 100  73  84  68  13  62]
 [ 60  24  40  72  72  66  21  44  99  67  69  19  51   9  11]
 [ 86  77  75  58  92  58   7  97  20  41  43  49  64  53  64]
 [  6  51  98   2   1  68  67  50  59  53  35  81  67  68  70]
 [ 10  54  32  16  33   1  39   3  61  23   5   6  62  46  60]
 [ 74  13  78  24  93  76  48  34  32  91   0  15  38  14  57]
 [ 15  56  70  61  89  69  89  62  37  14  83  54  83  73  93]
 [ 88   2  28   7  40  96  84  62   3  79  72  53  50  46  86]
 [ 40  69  31   6  44  23  20  31  61  48  26  73  75  83  48]]


In [7]:
random.randint(0, 100)

20

__Exercici 3__

Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

In [8]:
def random_array_2(rows, cols):
    arr = []
    for i in range(0, rows):
        row = []
        for j in range(0, cols):
            row.append(random.randint(0, 100))
        arr.append(row)
    arr = np.array(arr)
    return(arr)
    
def sums(arr):
    col_sum = np.sum(arr, axis = 0)
    row_sum = np.sum(arr, axis = 1)
    
    print('Suma de les columnes')
    print(col_sum)
    print('Suma de les files')
    print(row_sum)

In [9]:
sums(random_array_2(2, 3))

Suma de les columnes
[ 38 131  34]
Suma de les files
[ 91 112]


__Exercici 4__

Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.

In [10]:
# Intent 1

arr = np.array(random_array_2(2, 10))

#Calculem la mitjana de cada columna:

x_mean = 0
y_mean = 0

for i in range (0, len(arr[0])):
    x_mean += arr[0][i]/len(arr[0])

for i in range (0, len(arr[0])):
    y_mean += arr[1][i]/len(arr[1])

# Calculem la covariança. Primer els operadors del numerador:

oper_x = 0
oper_y = 0

for i in range (0, len(arr[0])):
    oper_x += arr[0][i] - x_mean

for i in range (0, len(arr[0])):
    oper_y += arr[1][i] - y_mean 
    
cov_xy = (oper_x * oper_y) / len(arr[0])

#Calculem la desviació estandard

num_x = 0

num_x += (arr[0][i] - x_mean)**2

num_y = 0

num_y += (arr[1][i] - y_mean)**2

desv_x = np.sqrt(num_x/len(arr[0]))
print(desv_x)
print(np.std(arr[0]))
desv_y = np.sqrt(num_y/len(arr[1]))
print(desv_y)
print(np.std(arr[1]))
print(np.std(arr, 1))

# Càlcul correlació

corr = cov_xy / (desv_x * desv_y)

print(corr)
print(np.corrcoef(arr[0], arr[1]))

1.644384383287556
23.903137869325857
0.5692099788303119
21.188676221038442
[23.90313787 21.18867622]
-5.178163890681484e-28
[[1.         0.41549859]
 [0.41549859 1.        ]]


In [56]:
# Intent 2

arr = np.array(random_array_2(2, 10))
#arr = np.array([[7, 14, 32, 52, 85, 91, 105, 121], [1, 2, 3, 3, 5, 5, 6, 6]])
arr = np.array([[22, 48, 76, 10, 22, 4, 68, 44, 10, 76, 14, 56], [63, 39, 61, 30, 51, 44, 74, 78, 55, 58, 41, 69]])

#Calculem la mitjana de cada columna:

x_mean = 0
y_mean = 0

for i in range (0, len(arr[0])):
    x_mean += arr[0][i]
    
x_mean = x_mean / len(arr[0])

for i in range (0, len(arr[0])):
    y_mean += arr[1][i]
    
y_mean = y_mean / len(arr[1])

print('x_mean')
print(x_mean)

print('y_mean')
print(y_mean)

# Calculem la covariança. Primer els operadors del numerador:

oper_x = 0
oper_y = 0
cov_xy = 0

for i in range (0, len(arr[0])):
    cov_xy += ((arr[0][i] - x_mean) * (arr[1][i] - y_mean)) / len(arr[0])
    
print('cov_xy')
print(cov_xy)

#Calculem la desviació estandar

num_x = 0
num_y = 0

for i in range (0, len(arr[0])):
    num_x += (arr[0][i] - x_mean)**2

for i in range (0, len(arr[0])):
    num_y += (arr[1][i] - y_mean)**2

desv_x = np.sqrt(num_x/len(arr[0]))
print(desv_x)
print(np.std(arr[0]))
desv_y = np.sqrt(num_y/len(arr[1]))
print(desv_y)
print(np.std(arr[1]))
print(np.std(arr, 1))

# Calculem la correlació

corr = cov_xy / (desv_x * desv_y)

print(corr)
print(np.corrcoef(arr[0], arr[1]))

x_mean
37.5
y_mean
55.25
cov_xy
207.45833333333331
25.911709064951054
25.911709064951054
14.16642156650719
14.16642156650719
[25.91170906 14.16642157]
0.5651642265418636
[[1.         0.56516423]
 [0.56516423 1.        ]]


In [57]:
# Format funció

def manual_corr(arr):

    #Calculem la mitjana de cada columna:

    x_mean = 0
    y_mean = 0

    for i in range (0, len(arr[0])):
        x_mean += arr[0][i]

    x_mean = x_mean / len(arr[0])

    for i in range (0, len(arr[0])):
        y_mean += arr[1][i]

    y_mean = y_mean / len(arr[1])

    # Calculem la covariança. Primer els operadors del numerador:

    oper_x = 0
    oper_y = 0
    cov_xy = 0

    for i in range (0, len(arr[0])):
        cov_xy += (arr[0][i] - x_mean) * (arr[1][i] - y_mean) / len(arr[0])

    #Calculem la desviació estandar

    num_x = 0
    num_y = 0

    for i in range (0, len(arr[0])):
        num_x += (arr[0][i] - x_mean)**2

    for i in range (0, len(arr[1])):
        num_y += (arr[1][i] - y_mean)**2

    desv_x = np.sqrt(num_x/len(arr[0]))

    desv_y = np.sqrt(num_y/len(arr[1]))

    # Calculem la correlació

    corr = cov_xy / (desv_x * desv_y)

    print(corr)
    return corr

In [58]:
# Proves càlcul manual correlació

arr_1 = random_array_2(2, 10)

arr_2 = np.array([[7, 14, 32, 52, 85, 91, 105, 121], [1, 2, 3, 3, 5, 5, 6, 6]])

arr_3 = np.array([[7, 14, 32, 52, 85, 91, 105, 121], [5, 5, 4, 3, 3, 2, 1, 0]])

print('Test random. Les variables, al prendre valors aleatoris, no mostraran correlació')
print('Correlació manual')
manual_corr(arr_1)
print('Correlació amb la funció de Numpy')
print(np.corrcoef(arr_1[0], arr_1[1]))

print('Test correlació positiva. Les dades de les variables estan correlacionades de tal forma que al creixer una, també ho fa l\'altra')
manual_corr(arr_2)
print(np.corrcoef(arr_2[0], arr_2[1]))

print('Test correlació negativa. Les dades de les variables estan correlacionades de tal forma que al creixer una, l\'altra decreix')
manual_corr(arr_3)
print(np.corrcoef(arr_3[0], arr_3[1]))


Test random. Les variables, al prendre valors aleatoris, no mostraran correlació
Correlació manual
0.10919521965567382
Correlació amb la funció de Numpy
[[1.         0.10919522]
 [0.10919522 1.        ]]
Test correlació positiva. Les dades de les variables estan correlacionades de tal forma que al creixer una, també ho fa l'altra
0.9813888179844993
[[1.         0.98138882]
 [0.98138882 1.        ]]
Test correlació negativa. Les dades de les variables estan correlacionades de tal forma que al creixer una, l'altra decreix
-0.9652006490640259
[[ 1.         -0.96520065]
 [-0.96520065  1.        ]]


In [29]:
arr

array([[ 78,  48,  75,  71,  49,  69,   0,  60,  28,  68],
       [ 88,  54,  95,   4,  53,  85,  32,  71, 100,  98]])

In [12]:
len(arr[0])

10

In [53]:
k_m = np.array([22, 48, 76, 10, 22, 4, 68, 44, 10, 76, 14, 56])
km = np.array([63, 39, 61, 30, 51, 44, 74, 78, 55, 58, 41, 69])

gns_k_m = 0
gns_km = 0
cov = 0
sum_k_m = 0
sum_km = 0

for k in range(len(k_m)):
    gns_k_m += k_m[k]/len(k_m)

for k in range(len(km)):
    gns_km += km[k]/len(km)
    
print(gns_k_m, gns_km)

for k in range(len(k_m)):
    cov += (k_m[k]-gns_k_m)*(km[k]-gns_km)/(len(k_m))

print(cov)

for k in range(len(k_m)):
    sum_k_m += (k_m[k]-gns_k_m)**2

sa_k_m = np.sqrt(sum_k_m/len(k_m))
print(sa_k_m)
print(np.std(k_m))

for k in range(len(km)):
    sum_km += (km[k]-gns_km)**2
    
sa_km = np.sqrt(sum_km/len(km))
print(sa_km)
print(np.std(km))

cor = cov/(sa_k_m*sa_km)

print(cor)
print(np.corrcoef(k_m,km))

37.5 55.25000000000001
207.45833333333334
25.911709064951054
25.911709064951054
14.16642156650719
14.16642156650719
0.5651642265418636
[[1.         0.56516423]
 [0.56516423 1.        ]]
